config/routes.rb
Rails.application.routes.draw do
  get 'groceries_list/edit'

  resource :dashboard, only: [:index]
  resource :line_items
  resource :groceries
  resources :grocery_list
  root to: "dashboard#index"
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
end

app/models/grocery_list.rb
class GroceryList < ActiveRecord::Base
  has_many :line_items
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :grocery
  
  def name
    self.grocery.name
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
class Admin::ApplicationController < Administrate::ApplicationController
  before_filter :authenticate_admin

  def authenticate_admin
    # TODO Add authentication logic here.
  end

  # Override this value to specify the number of elements to display at a time
  # on index pages. Defaults to 20.
  # def records_per_page
  #   params[:per_page] || 20
  # end
end

app/controllers/admin/groceries_controller.rb
module Admin
  class GroceriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Grocery.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Grocery.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @groceries = Grocery.all
    @line_items = GroceryList.last.line_items
    @groceries_list = GroceryList.last
  end
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  def new
    @grocery = Grocery.new
  end

  def create
    @grocery = Grocery.new(grocery_params)
    respond_to do |format|
      if @grocery.save
        format.html { redirect_to root_url, notice: 'Grocery was successfully created.' }
      else
        format.html { render :new}
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def grocery_params
    params.require(:grocery).permit(:name, :price)
  end
end

app/controllers/grocery_list_controller.rb
class GroceryListController < ApplicationController
  def edit
    @groceries_list = GroceryList.find(params[:id])
    @groceries_list_items = @groceries_list.line_items
  end

  private 
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_grocery_list, only: [:create, :update, :destroy]

  def new
  end

  def create
    if @grocery_list.line_items.find_by(grocery_id: line_item_params[:grocery_id]).present?
      @line_item = @grocery_list.line_items.find_by(grocery_id: line_item_params[:grocery_id])
      update_line_item(params, @line_item)
    else
      unless params[:quantity].to_i == -1
        @line_item = LineItem.create(
          grocery_list_id: @grocery_list.id,
          grocery_id: line_item_params[:grocery_id],
          quantity: 1
          )
        respond_to do |format|
          if @line_item.save
            format.js {render layout: false}
          end
        end
      end
    end
  end


  private

  def update_line_item(params, line_item)
    line_item.update_attributes(quantity: (line_item.quantity + params[:quantity].to_i))
    respond_to do |format|
      if @line_item.quantity == 0 
        line_item.delete
        format.js {render layout: false}
      else 
        @line_item.save
        format.js {render layout: false}        
      end
    end
  end
  

  def line_item_params
    params.permit(:id, :grocery_id, :quantity)
  end

  def set_grocery_list 
    @grocery_list = GroceryList.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/groceries_list_helper.rb
module GroceriesListHelper
end

app/helpers/grocery_helper.rb
module GroceryHelper
end

app/views/dashboard/_grocery_list.haml
%h1 Grocery List
- GroceryList.last.line_items.all.each do |line_item|
  %p
    = line_item.grocery.name
    = line_item.quantity
  

app/views/dashboard/index.html.haml
.cols-12.p-bottom
  = link_to "Add a new Grocery", new_groceries_path, class: "btn-solid btn-big btn-accent"  
.cols-12
  .cols-9
    = render @groceries
  .cols-3
    #grocery_list
      = render "grocery_list"
    = link_to "Checkout Grocery List", edit_grocery_list_path(GroceryList.last.id), class: "btn-solid btn-sml btn-accent"

app/views/groceries/_grocery.haml
.product-grid.m-w-100
  %h3.p-top.p-bottom.tac= grocery.name
  .cols-12.product-buttons  
    = link_to line_items_path(grocery_id: grocery, quantity: -1, groceries_page: true), method: :post, remote: true, class: "cols-6 product-buttons-border-right" do
      .fa.fa-minus
    = link_to line_items_path(grocery_id: grocery, quantity: 1, groceries_page: true), method: :post, remote: true, class: "cols-6" do
      .fa.fa-plus

app/views/groceries/new.haml
%h1 Add A Grocery

= simple_form_for(@grocery) do |f|
  = f.input :name
  = f.input :price
  = f.submit "Create", class: "btn-solid btn-accent btn-huge"

app/views/grocery_list/edit.html.haml
%h1 Edit Groceries List
= @groceries_list.inspect
%ul
  - @groceries_list_items.each do |i|
    %li 
      = i.name
      = i.quantity
= simple_form_for(@groceries_list, clasS: "l-form") do |g|
  = g.input :open
  = g.submit "Close list and send email", class: "btn-big btn-solid btn-accent"

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title House
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .l-section
      = yield

app/views/line_items/_line_item.haml
%p
  = line_item.grocery.name
  = line_item.quantity

app/views/line_items/create.js.erb
 $("#grocery_list").html("<%= j render("dashboard/grocery_list")%>");